server:
  port: 8099
spring:
  application:
    name: user-service
  cache:
    cache-names: user-cache
    redis:
      time-to-live: 600
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
user:
  minAge: 18